baseURL = "https://v1ctor.es"
languageCode = "en-us"
title = "Víctor Moreno"
theme = "hello-friend-ng"
paginate = "10"
[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04"

  # Subtitle for home
  homeSubtitle = "Systems Administrator // IT Consultant"

  # Set disableReadOtherPosts to true in order to hide the links to other posts.
  disableReadOtherPosts = false

  # Enable sharing buttons, if you linke
  enableSharingButtons = true

  # Metadata mostly used in document's head
  description = "My new homepage or blog"
  keywords = "homepage, blog"
  images = [""]

[taxonomies]
    category = "blog"
    tag      = "tags"
    series   = "series"

[languages]
  [languages.en]
    title = "Víctor Moreno"
    subtitle = "Systems Administrator // IT Consultant"
    keywords = ""
    copyright = '<a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">CC BY-NC 4.0</a>'
    readOtherPosts = "Read other posts"
[languages.es]
    title = "Víctor Moreno"
    subtitle = "Administrador de sistemas // Consultor IT"
    keywords = ""
    copyright = '<a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">CC BY-NC 4.0</a>'
    readOtherPosts = "Read other posts"

    [languages.en.params.logo]
      logoText = "v1ctormoreno"
      logoHomeLink = "/"
    # or
    #
    # path = "/img/your-example-logo.svg"
    # alt = "Your example logo alt text"

  # And you can even create generic menu
  [[menu.main]]
    identifier = "blog"
    name       = "Blog"
    url        = "https://blog.v1ctor.es"

  [[params.social]]
    name = "email"
    url  = "mailto:victor@victormoreno.es"

  [[params.social]]
    name = "github"
    url  = "https://github.com/v1ctormoreno"

  [[params.social]]
    name = "linkedin"
    url  = "https://www.linkedin.com/in/v1ctormoreno/"


